### PR TITLE
Avoid walking over entire load paths for simple precompile strings

### PR DESCRIPTION
**Pull request by josh**
Related #234.

/cc @rafaelfranca @dhh

### CODE REVIEW

**Comment by josh** [comment]
This stupid "loose asset block" is still going to be slow.

https://github.com/rails/sprockets-rails/blob/6ea7c602bb87e81d011780936cc024d95297ae7c/lib/sprockets/railtie.rb#L46-L49

**Comment by dhh** [comment]
Happy to test our suite against latest sprockets-rails to see what effect it has on the suite run time.

**Comment by rafaelfranca** [comment]
Looks good to me.

Right now I don't see how to remove the loose asset block and keep backward compatibility but maybe we should precompile only assets that are required using some of the existent APIs (like explicit `link` directive and assets helpers) in future versions.

**Comment by josh** [comment]
> Right now I don't see how to remove the loose asset block and keep backward compatibility but maybe we should precompile only assets that are required using some of the existent APIs (like explicit link directive and assets helpers) in future versions.

Yeah, thats the direction I'd like to head in.

Supporting the current Proc API inherently requires iteration over every logical path which is slow and error prone.

**Pull request merged**
