### PR TITLE
Prevent alias logical paths passed to asset_path

### PR DESCRIPTION
**Pull request by josh**
Cherry pick #241 into 2.x.

/cc @rafaelfranca

### CODE REVIEW

**Comment by josh** [comment]
@rafaelfranca if this looks good, are you cool with pushing this out in a new 2.x release?

**Comment by rafaelfranca** [comment]
Yeah, it is fine.

**Comment by matt-glover** [comment]
Seems that this change (or an extremely similar one) was reverted for the 3.x line [here](https://github.com/rails/sprockets-rails/pull/251).

Should the 2.x line receive a revert also?

**Comment by aprescott** [comment]
@matt-glover interesting. I'm certainly in favour of reverting this change for 2.x if it helps address all the problems described in #241 in relation rails/sprockets#36. I _think_ that's causing problems for us with `foo` vs `foo/index.js`. I was hoping to upgrade to Sprockets 3.x to try and resolve the matter, but sadly I'm blocked on `haml_coffee_assets` being locked on `~> 2.0`.

**Comment by aprescott** [comment]
@matt-glover looks like it was backported and released in 2.3.2. https://github.com/rails/sprockets-rails/issues/257

**Comment by matt-glover** [comment]
Looks great. This revert eliminated the spurious errors we were getting in development mode with the asset debug configuration enabled.

Thanks for the quick turnaround!

**Pull request merged**
