### PR TITLE
Bring quiet_assets to sprockets-rails

### PR DESCRIPTION
**Pull request by route**
As discussed here https://github.com/rails/rails/pull/24383 out of DHH comment here https://github.com/evrone/quiet_assets/issues/47#issuecomment-184186025
Again feel free to direct me and I'll fix everything that needs to be

### CODE REVIEW

**Comment by maclover7** [comment]
In general, :+1: on this. Would you be able to add a test case or two to test this functionality?

**Comment by route** [comment]
@maclover7 yep will do that

**Comment by connorshea** [comment]
:+1: nice! Wasn't sure how to implement this myself, so I'm glad you picked it up! Thank you!

**Comment by connorshea** [comment]
@maclover7 would you be alright with adding this to the 5.0.0 milestone? Or 5.1.0 at least.

@route any updates on those tests? :)

**Comment by maclover7** [comment]
@connorshea I don't think adding to a 5.x milestone is necessary -- as far as I can tell, this isn't a release blocker, but more of a new feature being added.

**Comment by connorshea** [comment]
@route any progress on this?

**Comment by connorshea** [comment]
@maclover7 Is there any policy on picking up and finishing abandoned pull requests like this?

**Comment by route** [comment]
Sorry guys, I'll try to make it this weekend, too many things. If not feel free to pick it up

**Comment by kmcphillips** [comment]
This is great 👍

**Comment by rafaelfranca** [comment]
Thanks! Merged in #338

**Comment by connorshea** [comment]
@rafaelfranca I think you mean #355

**Pull request closed without merging**
