### PR TITLE
Fix 2.x build

### LINKED ISSUE #242: 2.x branch build is broken
Looks like its related to internal changes around the sprockets 3.x final release.

https://travis-ci.org/rails/sprockets-rails/builds/58168802

### PR DESCRIPTION
**Pull request by josh**
Trying to fix test failures on the 2.x branch.

Closes #242

### CODE REVIEW

**Comment by josh** [comment]
Hmm, its having trouble trying to resolve the rack gem on some of the tests.

https://travis-ci.org/rails/sprockets-rails/jobs/61411993

```
Bundler could not find compatible versions for gem "rack":
  In Gemfile:
    sprockets-rails (>= 0) ruby depends on
      actionpack (>= 3.0) ruby depends on
        rack (~> 1.2.1) ruby
    sprockets (~> 3.0.0) ruby depends on
      rack (1.0.0)
```

I don't quite get it. It works locally here.

```
$ BUNDLE_GEMFILE=$PWD/test/gemfiles/Gemfile.sprockets-3.0.x bundle install
Resolving dependencies...
Using rake 10.4.2
Using i18n 0.7.0
Using minitest 4.7.3
Using multi_json 1.11.0
Using thread_safe 0.3.5
Using tzinfo 0.3.44
Using activesupport 4.0.13
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.2
Using rack-test 0.6.3
Using actionpack 4.0.13
Using execjs 2.5.2
Using json 1.8.2
Using thor 0.19.1
Using railties 4.0.13
Using sass 3.4.13
Using sprockets 3.0.3
Using sprockets-rails 2.2.4 from source at ./../..
Using uglifier 2.7.1
Using bundler 1.9.6
Bundle complete! 8 Gemfile dependencies, 21 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
```

@rafaelfranca any ideas?

**Comment by rafaelfranca** [comment]
Looking :eyes:

**Comment by rafaelfranca** [comment]
It seems to be a bundler 1.7.6 bug. I'll bump the version on .travis.yml but we will lost the cache, but it is fine, we can remove it later when travis upgrade.

**Comment by josh** [comment]
Oh, rad, we're green! Thanks @rafaelfranca!

**Pull request merged**
